apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: argocd-web
  namespace: argocd
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: cilium-gw
      namespace: kube-system
      sectionName: https-gw
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /argo
      backendRefs:
        - name: argocd-server
          namespace: argocd
          port: 80
